name: CI

on:
  push:
    branches: [ main, master, deno ]
  pull_request:
    branches: [ main, master, deno ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [2.x, 2.3.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: ${{ matrix.deno-version }}

    - name: Verify Deno installation
      run: deno --version

    - name: Check TypeScript compilation
      run: deno check src/cli.ts

    - name: Run tests
      run: deno test --allow-read --allow-write --allow-run --allow-env

    - name: Run linter
      run: deno lint

    - name: Run formatter check
      run: deno fmt --check

    - name: Build binary (Ubuntu)
      run: deno compile --allow-read --allow-write --allow-run --allow-env --output=wezterminator-linux src/cli.ts

    - name: Test binary execution
      run: |
        ./wezterminator-linux || test $? -eq 1
        echo "Binary execution test completed"

  build-cross-platform:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/deno'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: 2.x

    - name: Build for multiple platforms
      run: |
        # Linux x86_64
        deno compile --target x86_64-unknown-linux-gnu --allow-read --allow-write --allow-run --allow-env --output=dist/wezterminator-linux src/cli.ts

        # macOS x86_64
        deno compile --target x86_64-apple-darwin --allow-read --allow-write --allow-run --allow-env --output=dist/wezterminator-macos-intel src/cli.ts

        # macOS ARM64
        deno compile --target aarch64-apple-darwin --allow-read --allow-write --allow-run --allow-env --output=dist/wezterminator-macos-arm64 src/cli.ts

        # Windows x86_64
        deno compile --target x86_64-pc-windows-msvc --allow-read --allow-write --allow-run --allow-env --output=dist/wezterminator-windows.exe src/cli.ts

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wezterminator-binaries
        path: dist/
        retention-days: 30

  security-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: 2.x

    - name: Security audit
      run: |
        # Check for known vulnerabilities in dependencies
        deno info src/cli.ts

        # Verify permissions are minimal
        echo "Checking required permissions..."
        grep -r "allow-" src/ || true