name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target:
          - name: linux
            target: x86_64-unknown-linux-gnu
            output: wezterminator-linux
          - name: macos-intel
            target: x86_64-apple-darwin
            output: wezterminator-macos-intel
          - name: macos-arm64
            target: aarch64-apple-darwin
            output: wezterminator-macos-arm64
          - name: windows
            target: x86_64-pc-windows-msvc
            output: wezterminator-windows.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: 2.x

    - name: Build binary
      run: |
        deno compile \
          --target ${{ matrix.target.target }} \
          --allow-read \
          --allow-write \
          --allow-run \
          --allow-env \
          --output=${{ matrix.target.output }} \
          src/cli.ts

    - name: Create Release and Upload Assets
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ matrix.target.output }}
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}